---
- name: trying debug from git
  hosts: production
  tasks:
    - name: debug from git
      debug:
        msg: TODAY is Saturday

    - name: install applications
      yum:
        name: "{{ webpackages }}"
        state: present

    - name: start application
      service:
        name: "{{ webpackages }}"
        state: started
        enabled: yes
